// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:reading_diary/models/book.dart';
import 'package:reading_diary/models/diary_entry.dart';
import 'package:reading_diary/models/setting.dart';
import 'package:reading_diary/models/wish.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BookAdapter());
    registerAdapter(DiaryEntryAdapter());
    registerAdapter(SettingAdapter());
    registerAdapter(WishAdapter());
  }
}
